name: key-pair-w-toml

on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.11.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.11.x

      - name: Decrypt RSA key
        run: |
          echo "${{ secrets.SF_PRIVATE_KEY }}" > rsa_key.p8
          chmod 600 rsa_key.p8

      - name: Create connections.toml
        run: |
          cat <<EOF > .github/workflows/connections.toml
          account = "${{ secrets.SF_ACCOUNT }}"
          user = "${{ secrets.SF_USERNAME }}"
          role = "${{ secrets.SF_ROLE }}"
          warehouse = "${{ secrets.SF_WAREHOUSE }}"
          database = "${{ secrets.SF_DATABASE }}"
          private_key_file = "rsa_key.p8"
          private_key_file_pwd = "${{ secrets.SF_PRIVATE_KEY_PASSPHRASE }}"
          EOF



      - name: Changing Permissions of connections.toml file
        run: |
          chown $USER ".github/workflows/connections.toml"
          chmod 0600 ".github/workflows/connections.toml"
          
      - name: Run schemachange
        run: |
          echo "Installing schemachange"
          pip install schemachange

          echo "Running schemachange"
          schemachange -f migrations --connections-file-path .github/workflows/connections.toml 
      - name: Clean up sensitive files
        run: rm -f rsa_key.p8 connections.toml
